# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5a955f95e120556d74fd20cf95babc6b828c528a54f298fa4a9fabd10545af80f40dd5a800f9549ca102096ae60a66a889cfeddc7abe578c8d28fc11ba54e6b9

test:
  secret_key_base: 1565e12330f24acd455dc7cdd4eeba6d82e635993e3e6bd3b9825f15922e6cae567c693305b45ade5bfbda0ade71dff9cb0263604eea6cfdb0e99f39279ea001

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
